export const ARRAY = "Array"
export const LINKED_LIST = "Linked List"
export const GRAPH = "Graph"
export const BINARY_TREE = "Binary Tree"
export const SORTING = "Sorting"
export const BUBBLE_SORT = "Bubble Sort"
export const QUICK_SORT = "Quick Sort"

export const SEARCHING = "Searching"
export const BINARY_SEARCH = "Binary Search"